// <auto-generated />
using System;
using System.Net;
using EntityFrameworkProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EntityFrameworkProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251120193344_SpuSku")]
    partial class SpuSku
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("Npgsql:PostgresExtension:citext", ",,")
                .HasAnnotation("Npgsql:PostgresExtension:uuid-ossp", ",,")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EntityFrameworkProject.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AccessToken")
                        .HasColumnName("access_token")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AccessTokenExpiresAt")
                        .HasColumnName("access_token_expires_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnName("account_id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("IdToken")
                        .HasColumnName("id_token")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastPasswordChange")
                        .HasColumnName("last_password_change")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Password")
                        .HasColumnName("password")
                        .HasColumnType("text");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnName("provider_id")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnName("refresh_token")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnName("refresh_token_expires_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResetToken")
                        .HasColumnName("reset_token")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnName("reset_token_expires")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Scope")
                        .HasColumnName("scope")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnName("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasName("account_user_id_idx");

                    b.HasIndex("ProviderId", "AccountId")
                        .IsUnique()
                        .HasName("account_provider_account_unique");

                    b.ToTable("account");
                });

            modelBuilder.Entity("EntityFrameworkProject.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnName("organization_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnName("parent_id")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .HasColumnName("path")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnName("slug")
                        .HasColumnType("citext");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .HasName("ix_category_org");

                    b.HasIndex("ParentId");

                    b.HasIndex("OrganizationId", "ParentId")
                        .HasName("ix_category_org_parent");

                    b.HasIndex("OrganizationId", "Slug")
                        .IsUnique()
                        .HasName("ux_category_org_slug");

                    b.ToTable("category");
                });

            modelBuilder.Entity("EntityFrameworkProject.Models.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnName("organization_id")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnName("role")
                        .HasColumnType("text");

                    b.Property<Guid?>("TeamId")
                        .HasColumnName("team_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnName("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .HasName("memberships_organization_id_idx");

                    b.HasIndex("UserId")
                        .HasName("memberships_user_id_idx");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique()
                        .HasName("memberships_org_user_unique");

                    b.ToTable("memberships");
                });

            modelBuilder.Entity("EntityFrameworkProject.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Logo")
                        .HasColumnName("logo")
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("metadata")
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnName("slug")
                        .HasColumnType("citext");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasName("organization_slug_unique");

                    b.ToTable("organization");
                });

            modelBuilder.Entity("EntityFrameworkProject.Models.ProductAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsVariant")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("is_variant")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnName("organization_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .HasName("ix_product_attribute_org");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasName("ux_product_attribute_org_code");

                    b.ToTable("product_attribute");
                });

            modelBuilder.Entity("EntityFrameworkProject.Models.ProductAttributeValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("AttributeId")
                        .HasColumnName("attribute_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("sort_order")
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnName("value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId")
                        .HasName("ix_product_attribute_value_attribute_id");

                    b.HasIndex("AttributeId", "Value")
                        .IsUnique()
                        .HasName("ux_product_attribute_value");

                    b.ToTable("product_attribute_value");
                });

            modelBuilder.Entity("EntityFrameworkProject.Models.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AltText")
                        .HasColumnName("alt_text")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsMain")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("is_main")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ProductTemplateId")
                        .HasColumnName("product_template_id")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("sort_order")
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnName("url")
                        .HasColumnType("text");

                    b.Property<Guid?>("VariantId")
                        .HasColumnName("variant_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductTemplateId")
                        .IsUnique()
                        .HasName("ux_product_image_main_template")
                        .HasFilter("is_main = true AND variant_id IS NULL");

                    b.HasIndex("VariantId")
                        .HasName("ix_product_image_variant");

                    b.ToTable("product_image");
                });

            modelBuilder.Entity("EntityFrameworkProject.Models.ProductTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AggregatorCode")
                        .HasColumnName("aggregator_code")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .HasColumnName("brand")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnName("created_by_user_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnName("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("text");

                    b.Property<short?>("FreightMode")
                        .HasColumnName("freight_mode")
                        .HasColumnType("smallint");

                    b.Property<bool>("HasDelivery")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("has_delivery")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsRental")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("is_rental")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsService")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("is_service")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<string>("Nbs")
                        .HasColumnName("nbs")
                        .HasColumnType("text");

                    b.Property<string>("Ncm")
                        .HasColumnName("ncm")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnName("organization_id")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnName("slug")
                        .HasColumnType("citext");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("WarrantyMonths")
                        .HasColumnName("warranty_months")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("OrganizationId")
                        .HasName("ix_product_template_org");

                    b.HasIndex("OrganizationId", "AggregatorCode")
                        .IsUnique()
                        .HasName("ux_product_template_org_aggregator")
                        .HasFilter("aggregator_code IS NOT NULL");

                    b.HasIndex("OrganizationId", "Slug")
                        .IsUnique()
                        .HasName("ux_product_template_org_slug");

                    b.ToTable("product_template");
                });

            modelBuilder.Entity("EntityFrameworkProject.Models.ProductTemplateAttributeValue", b =>
                {
                    b.Property<Guid>("ProductTemplateId")
                        .HasColumnName("product_template_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributeValueId")
                        .HasColumnName("attribute_value_id")
                        .HasColumnType("uuid");

                    b.HasKey("ProductTemplateId", "AttributeValueId");

                    b.HasIndex("AttributeValueId");

                    b.ToTable("product_template_attribute_value");
                });

            modelBuilder.Entity("EntityFrameworkProject.Models.ProductTemplateCategory", b =>
                {
                    b.Property<Guid>("ProductTemplateId")
                        .HasColumnName("product_template_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnName("category_id")
                        .HasColumnType("uuid");

                    b.HasKey("ProductTemplateId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("product_template_category");
                });

            modelBuilder.Entity("EntityFrameworkProject.Models.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Barcode")
                        .HasColumnName("barcode")
                        .HasColumnType("text");

                    b.Property<decimal?>("Cost")
                        .HasColumnName("cost")
                        .HasColumnType("numeric(15,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnName("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("text");

                    b.Property<decimal?>("Height")
                        .HasColumnName("height")
                        .HasColumnType("numeric(12,2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("is_active")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Length")
                        .HasColumnName("length")
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnName("organization_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductTemplateId")
                        .HasColumnName("product_template_id")
                        .HasColumnType("uuid");

                    b.Property<string>("RawVariationDescription")
                        .HasColumnName("raw_variation_description")
                        .HasColumnType("text");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnName("sku")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("Weight")
                        .HasColumnName("weight")
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("Width")
                        .HasColumnName("width")
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductTemplateId")
                        .HasName("ix_product_variant_product_template_id");

                    b.HasIndex("OrganizationId", "Sku")
                        .IsUnique()
                        .HasName("ux_product_variant_org_sku");

                    b.ToTable("product_variant");
                });

            modelBuilder.Entity("EntityFrameworkProject.Models.ProductVariantAttributeValue", b =>
                {
                    b.Property<Guid>("VariantId")
                        .HasColumnName("variant_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributeValueId")
                        .HasColumnName("attribute_value_id")
                        .HasColumnType("uuid");

                    b.HasKey("VariantId", "AttributeValueId");

                    b.HasIndex("AttributeValueId");

                    b.ToTable("product_variant_attribute_value");
                });

            modelBuilder.Entity("EntityFrameworkProject.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("ActiveOrganizationId")
                        .HasColumnName("active_organization_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnName("expires_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnName("ip_address")
                        .HasColumnType("inet");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnName("token")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserAgent")
                        .HasColumnName("user_agent")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnName("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActiveOrganizationId");

                    b.HasIndex("ExpiresAt")
                        .HasName("session_expires_at_idx");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasName("session_token_unique");

                    b.HasIndex("UserId")
                        .HasName("session_user_id_idx");

                    b.ToTable("session");
                });

            modelBuilder.Entity("EntityFrameworkProject.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasColumnType("citext");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("email_verified")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Image")
                        .HasColumnName("image")
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("metadata")
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("role")
                        .HasColumnType("text")
                        .HasDefaultValue("user");

                    b.Property<bool>("TwoFactorEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("two_factor_enabled")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasName("user_email_unique");

                    b.ToTable("user");
                });

            modelBuilder.Entity("EntityFrameworkProject.Models.Account", b =>
                {
                    b.HasOne("EntityFrameworkProject.Models.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .HasConstraintName("account_user_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityFrameworkProject.Models.Category", b =>
                {
                    b.HasOne("EntityFrameworkProject.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("category_organization_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFrameworkProject.Models.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("category_parent_fk")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("EntityFrameworkProject.Models.Membership", b =>
                {
                    b.HasOne("EntityFrameworkProject.Models.Organization", "Organization")
                        .WithMany("Memberships")
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("memberships_organization_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFrameworkProject.Models.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .HasConstraintName("memberships_user_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityFrameworkProject.Models.ProductAttribute", b =>
                {
                    b.HasOne("EntityFrameworkProject.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("product_attribute_organization_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityFrameworkProject.Models.ProductAttributeValue", b =>
                {
                    b.HasOne("EntityFrameworkProject.Models.ProductAttribute", "Attribute")
                        .WithMany("Values")
                        .HasForeignKey("AttributeId")
                        .HasConstraintName("product_attribute_value_attribute_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityFrameworkProject.Models.ProductImage", b =>
                {
                    b.HasOne("EntityFrameworkProject.Models.ProductTemplate", "ProductTemplate")
                        .WithMany("Images")
                        .HasForeignKey("ProductTemplateId")
                        .HasConstraintName("product_image_template_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFrameworkProject.Models.ProductVariant", "Variant")
                        .WithMany("Images")
                        .HasForeignKey("VariantId")
                        .HasConstraintName("product_image_variant_fk")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EntityFrameworkProject.Models.ProductTemplate", b =>
                {
                    b.HasOne("EntityFrameworkProject.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .HasConstraintName("product_template_created_by_user_fk")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EntityFrameworkProject.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("product_template_organization_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityFrameworkProject.Models.ProductTemplateAttributeValue", b =>
                {
                    b.HasOne("EntityFrameworkProject.Models.ProductAttributeValue", "AttributeValue")
                        .WithMany("TemplateValues")
                        .HasForeignKey("AttributeValueId")
                        .HasConstraintName("product_template_attribute_value_value_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFrameworkProject.Models.ProductTemplate", "ProductTemplate")
                        .WithMany("AttributeValues")
                        .HasForeignKey("ProductTemplateId")
                        .HasConstraintName("product_template_attribute_value_template_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityFrameworkProject.Models.ProductTemplateCategory", b =>
                {
                    b.HasOne("EntityFrameworkProject.Models.Category", "Category")
                        .WithMany("ProductTemplates")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("product_template_category_category_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFrameworkProject.Models.ProductTemplate", "ProductTemplate")
                        .WithMany("Categories")
                        .HasForeignKey("ProductTemplateId")
                        .HasConstraintName("product_template_category_template_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityFrameworkProject.Models.ProductVariant", b =>
                {
                    b.HasOne("EntityFrameworkProject.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("product_variant_organization_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFrameworkProject.Models.ProductTemplate", "ProductTemplate")
                        .WithMany("Variants")
                        .HasForeignKey("ProductTemplateId")
                        .HasConstraintName("product_variant_template_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityFrameworkProject.Models.ProductVariantAttributeValue", b =>
                {
                    b.HasOne("EntityFrameworkProject.Models.ProductAttributeValue", "AttributeValue")
                        .WithMany("VariantValues")
                        .HasForeignKey("AttributeValueId")
                        .HasConstraintName("product_variant_attribute_value_value_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFrameworkProject.Models.ProductVariant", "Variant")
                        .WithMany("AttributeValues")
                        .HasForeignKey("VariantId")
                        .HasConstraintName("product_variant_attribute_value_variant_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityFrameworkProject.Models.Session", b =>
                {
                    b.HasOne("EntityFrameworkProject.Models.Organization", "ActiveOrganization")
                        .WithMany("ActiveSessions")
                        .HasForeignKey("ActiveOrganizationId")
                        .HasConstraintName("session_active_org_fk")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EntityFrameworkProject.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .HasConstraintName("session_user_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
